/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.barmeier.nbpre.options;

import java.io.File;
import org.openide.util.NbPreferences;

public final class PalmSDKSettingsPanel extends javax.swing.JPanel {

    private final PalmSDKSettingsOptionsPanelController controller;

    PalmSDKSettingsPanel(PalmSDKSettingsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palmInspectorLabel = new javax.swing.JLabel();
        palmInspectorTextField = new javax.swing.JTextField();
        palmEmulatorLabel = new javax.swing.JLabel();
        palmEmulatorTextField = new javax.swing.JTextField();
        palmGeneratorLabel = new javax.swing.JLabel();
        palmGeneratorTextField = new javax.swing.JTextField();
        palmInstallerLabel = new javax.swing.JLabel();
        palmInstallerTextField = new javax.swing.JTextField();
        palmLauncherLabel = new javax.swing.JLabel();
        palmLauncherTextField = new javax.swing.JTextField();
        palmLoggerLabel = new javax.swing.JLabel();
        palmLoggerTextField = new javax.swing.JTextField();
        palmPackerLabel = new javax.swing.JLabel();
        palmPackerTextField = new javax.swing.JTextField();
        palmWormLabel = new javax.swing.JLabel();
        palmWormTextField = new javax.swing.JTextField();
        useSamePathCheckBox = new javax.swing.JCheckBox();
        vendorIdLabel = new javax.swing.JLabel();
        vendorIdTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(495, 294));

        org.openide.awt.Mnemonics.setLocalizedText(palmInspectorLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmInspectorLabel.text")); // NOI18N

        palmInspectorTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmInspectorTextField.text")); // NOI18N
        palmInspectorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pathCharHandler(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(palmEmulatorLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmEmulatorLabel.text")); // NOI18N

        palmEmulatorTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmEmulatorTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmGeneratorLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmGeneratorLabel.text")); // NOI18N

        palmGeneratorTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmGeneratorTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmInstallerLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmInstallerLabel.text")); // NOI18N

        palmInstallerTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmInstallerTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmLauncherLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmLauncherLabel.text")); // NOI18N

        palmLauncherTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmLauncherTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmLoggerLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmLoggerLabel.text")); // NOI18N

        palmLoggerTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmLoggerTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmPackerLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmPackerLabel.text")); // NOI18N

        palmPackerTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmPackerTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(palmWormLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmWormLabel.text")); // NOI18N

        palmWormTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.palmWormTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(useSamePathCheckBox, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.useSamePathCheckBox.text")); // NOI18N
        useSamePathCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSamePathCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(vendorIdLabel, org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.vendorIdLabel.text")); // NOI18N

        vendorIdTextField.setText(org.openide.util.NbBundle.getMessage(PalmSDKSettingsPanel.class, "PalmSDKSettingsPanel.vendorIdTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(useSamePathCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vendorIdLabel)
                        .addGap(85, 85, 85)
                        .addComponent(vendorIdTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palmLauncherLabel)
                            .addComponent(palmInstallerLabel)
                            .addComponent(palmWormLabel)
                            .addComponent(palmLoggerLabel)
                            .addComponent(palmPackerLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(palmEmulatorLabel)
                                .addComponent(palmInspectorLabel)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(palmGeneratorLabel)
                                    .addGap(7, 7, 7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palmWormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmPackerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmGeneratorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmInspectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmInstallerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmEmulatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmLoggerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palmLauncherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorIdLabel)
                    .addComponent(vendorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(useSamePathCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmInspectorLabel)
                    .addComponent(palmInspectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmEmulatorLabel)
                    .addComponent(palmEmulatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmGeneratorLabel)
                    .addComponent(palmGeneratorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmInstallerLabel)
                    .addComponent(palmInstallerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmLauncherLabel)
                    .addComponent(palmLauncherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmLoggerLabel)
                    .addComponent(palmLoggerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmPackerLabel)
                    .addComponent(palmPackerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmWormLabel)
                    .addComponent(palmWormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adjustPathes() {
        String typed = new File(palmInspectorTextField.getText()).getParent();
        palmEmulatorTextField.setText(typed+File.separator+"palm-emulator");
        palmGeneratorTextField.setText(typed+File.separator+"palm-generate");
        palmInstallerTextField.setText(typed+File.separator+"palm-install");
        palmLauncherTextField.setText(typed+File.separator+"palm-launch");
        palmPackerTextField.setText(typed+File.separator+"palm-package");
        palmLoggerTextField.setText(typed+File.separator+"palm-log");
        palmWormTextField.setText(typed+File.separator+"palm-worm");
    }

    private void pathCharHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathCharHandler
       if (useSamePathCheckBox.isSelected()) {
            adjustPathes();
       }
    }//GEN-LAST:event_pathCharHandler

    private void useSamePathCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSamePathCheckBoxActionPerformed
        palmEmulatorTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmGeneratorTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmInstallerTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmLauncherTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmPackerTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmLoggerTextField.setEnabled(!useSamePathCheckBox.isSelected());
        palmWormTextField.setEnabled(!useSamePathCheckBox.isSelected());
    }//GEN-LAST:event_useSamePathCheckBoxActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(PalmSDKSettingsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(PalmSDKSettingsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        useSamePathCheckBox.setSelected(NbPreferences.forModule(PalmSDKSettingsPanel.class).getBoolean("useSamePath", false));
        palmInspectorTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("inspector", ""));
        palmEmulatorTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("emulator", ""));
        palmGeneratorTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("generator", ""));
        palmInstallerTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("installer", ""));
        palmLauncherTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("launcher", ""));
        palmPackerTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("packer", ""));
        palmLoggerTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("logger", ""));
        palmWormTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("worm", ""));
        vendorIdTextField.setText(NbPreferences.forModule(PalmSDKSettingsPanel.class).get("vendorId", ""));
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(PalmSDKSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(PalmSDKSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).putBoolean("useSamePath", useSamePathCheckBox.isSelected());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("inspector", palmInspectorTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("emulator", palmEmulatorTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("generator", palmGeneratorTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("installer", palmInstallerTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("launcher", palmLauncherTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("packer", palmPackerTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("logger", palmLoggerTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("worm", palmWormTextField.getText());
        NbPreferences.forModule(PalmSDKSettingsPanel.class).put("vendorId", vendorIdTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel palmEmulatorLabel;
    private javax.swing.JTextField palmEmulatorTextField;
    private javax.swing.JLabel palmGeneratorLabel;
    private javax.swing.JTextField palmGeneratorTextField;
    private javax.swing.JLabel palmInspectorLabel;
    private javax.swing.JTextField palmInspectorTextField;
    private javax.swing.JLabel palmInstallerLabel;
    private javax.swing.JTextField palmInstallerTextField;
    private javax.swing.JLabel palmLauncherLabel;
    private javax.swing.JTextField palmLauncherTextField;
    private javax.swing.JLabel palmLoggerLabel;
    private javax.swing.JTextField palmLoggerTextField;
    private javax.swing.JLabel palmPackerLabel;
    private javax.swing.JTextField palmPackerTextField;
    private javax.swing.JLabel palmWormLabel;
    private javax.swing.JTextField palmWormTextField;
    private javax.swing.JCheckBox useSamePathCheckBox;
    private javax.swing.JLabel vendorIdLabel;
    private javax.swing.JTextField vendorIdTextField;
    // End of variables declaration//GEN-END:variables
}
